name : Web Branding Diva
brand : Web Branding Diva
description : Web Branding Diva site
keyword : 
url : http://redsirendesign.github.io/webbrandingdiva/
email : masha@redsirendesign.com
twitter : redsirendesign
github : redsirendesign
author : Red Siren Design
analytics : 
year : 2015
markdown : kramdown
exclude :
  - node_modules
